In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from pandas import set_option
import sklearn as sk
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import decomposition
from sklearn import preprocessing

In [9]:
filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data - Balanceada.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
795    3  2.52  1.72     2     0  ...      0      1      0   74     True
796    3  2.52  1.72     1     0  ...      0      1      0   71     True
797    2  4.04  2.76     1     0  ...      0      1      0   55     True
798    3  2.48  1.84     1     0  ...      0      1      0   55     True
799    4  3.44  2.16     1     0  ...      0      1      0   57     True

[800 rows x 17 columns]

In [10]:
data_set=sk.utils.shuffle(data_set)
data_set

DGN  PRE4   PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
765    3  3.04   3.60     1     0  ...      0      1      0   62     True
294    2  2.64   1.92     1     0  ...      0      1      0   63    False
177    3  3.04   2.32     1     0  ...      0      1      0   59    False
112    3  3.68  64.10     0     0  ...      0      1      0   60    False
424    4  2.81   2.31     1     1  ...      0      1      0   58    False
..   ...   ...    ...   ...   ...  ...    ...    ...    ...  ...      ...
504    2  2.80   1.60     1     0  ...      0      1      0   53     True
690    3  2.64   2.12     1     0  ...      0      1      0   72     True
473    2  3.98   3.06     2     0  ...      0      1      0   80     True
37     3  3.68   2.44     1     0  ...      0      0      0   61    False
571    3  2.68   2.40     0     0  ...      0      1      0   60     True

[800 rows x 17 columns]

In [11]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [12]:
labels = labels.astype('int')
labels

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [14]:
pca = decomposition.PCA(n_components=6)
pca.fit(features)
feature_PCA_Scaler = pca.transform(features)

In [15]:
scaler = preprocessing.StandardScaler().fit(feature_PCA_Scaler)
feature_PCA_Scaler = scaler.transform(feature_PCA_Scaler)

In [16]:
validation_size = 0.2
seed = 7
X_trainScaler, X_validationScaler, Y_trainScaler, Y_validationScaler = train_test_split(feature_PCA_Scaler, labels, 
                                                                                        test_size=validation_size, 
                                                                                        random_state=seed)

In [17]:
KNN = KNeighborsClassifier()
KNN.fit(X_trainScaler, Y_trainScaler)
predictions = KNN.predict(X_validationScaler)

In [18]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.76875
Matriz de confusion


array([[51, 37],
       [ 0, 72]])

In [19]:
LR = LogisticRegression()
LR.fit(X_trainScaler, Y_trainScaler)
predictions = LR.predict(X_validationScaler)

In [20]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.60625
Matriz de confusion


array([[51, 37],
       [26, 46]])

In [21]:
DT = DecisionTreeClassifier()
DT.fit(X_trainScaler, Y_trainScaler)
predictions =DT.predict(X_validationScaler)

In [22]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.8875
Matriz de confusion


array([[70, 18],
       [ 0, 72]])

In [23]:
SVM = SVC()
SVM.fit(X_trainScaler, Y_trainScaler)
predictions = SVM.predict(X_validationScaler)

In [24]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.675
Matriz de confusion


array([[48, 40],
       [12, 60]])

In [25]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier()
RF.fit(X_trainScaler, Y_trainScaler)
predictions = RF.predict(X_validationScaler)

In [26]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.95
Matriz de confusion


array([[80,  8],
       [ 0, 72]])