In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:

import random
import pandas as pd
import numpy as np
from pandas.plotting import scatter_matrix
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import seaborn as sns


filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data - Balanceada.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
795    3  2.52  1.72     2     0  ...      0      1      0   74     True
796    3  2.52  1.72     1     0  ...      0      1      0   71     True
797    2  4.04  2.76     1     0  ...      0      1      0   55     True
798    3  2.48  1.84     1     0  ...      0      1      0   55     True
799    4  3.44  2.16     1     0  ...      0      1      0   57     True

[800 rows x 17 columns]

In [39]:
data_set=sk.utils.shuffle(data_set)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
282    3  3.16  2.60     1     1  ...      0      0      0   69    False
130    3  3.32  2.87     1     0  ...      0      1      0   63    False
215    2  2.66  8.56     1     0  ...      0      1      0   61    False
400    3  2.48  1.60     0     0  ...      0      0      0   61    False
83     3  2.84  2.36     1     0  ...      0      0      0   62    False
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
726    3  2.52  1.72     1     0  ...      0      1      0   71     True
61     3  3.04  2.04     2     0  ...      0      1      0   77    False
214    3  2.96  2.32     0     0  ...      0      1      0   51    False
222    3  4.80  3.41     1     0  ...      0      1      0   54    False
40     5  3.80  2.98     1     0  ...      0      1      0   60     True

[800 rows x 17 columns]

In [40]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [41]:
labels=labels.astype('int')
labels

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [42]:
features

DGN  PRE4  PRE5  PRE6  PRE7  PRE8  ...  PRE17  PRE19  PRE25  PRE30  PRE32  AGE
282    3  3.16  2.60     1     1     0  ...      0      0      0      0      0   69
130    3  3.32  2.87     1     0     0  ...      0      0      0      1      0   63
215    2  2.66  8.56     1     0     1  ...      0      0      0      1      0   61
400    3  2.48  1.60     0     0     0  ...      0      0      0      0      0   61
83     3  2.84  2.36     1     0     0  ...      1      0      0      0      0   62
..   ...   ...   ...   ...   ...   ...  ...    ...    ...    ...    ...    ...  ...
726    3  2.52  1.72     1     0     0  ...      0      0      0      1      0   71
61     3  3.04  2.04     2     0     0  ...      0      0      0      1      0   77
214    3  2.96  2.32     0     0     0  ...      0      0      0      1      0   51
222    3  4.80  3.41     1     0     0  ...      0      0      0      1      0   54
40     5  3.80  2.98     1     0     0  ...      0      0      0      1      0   60

[800 rows x 16 columns]

In [43]:
labels.shape, features.shape

((800,), (800, 16))

In [44]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(features, labels, test_size=validation_size, random_state=seed)

In [45]:
X_train.shape, X_validation.shape, Y_train.shape, Y_validation.shape

((640, 16), (160, 16), (640,), (160,))

In [46]:
KNN=KNeighborsClassifier()
LR=LogisticRegression()

In [47]:
KNN.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [48]:
KNN.score(X_validation,Y_validation)

0.75

In [49]:
predic=KNN.predict(X_validation)
predic

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [50]:
predic==Y_validation

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
        True, False,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False, False,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True, False, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [51]:
print(accuracy_score(Y_validation, predic))
print(confusion_matrix(Y_validation, predic))
print(classification_report(Y_validation, predic))

0.75
[[46 37]
 [ 3 74]]
              precision    recall  f1-score   support

           0       0.94      0.55      0.70        83
           1       0.67      0.96      0.79        77

    accuracy                           0.75       160
   macro avg       0.80      0.76      0.74       160
weighted avg       0.81      0.75      0.74       160



In [34]:
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(KNN, features, labels, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % ('KNN', cv_results.mean(), cv_results.std())
print(msg)

KNN: 0.817500 (0.055958)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
