In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from pandas import set_option
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import decomposition
from sklearn import preprocessing



In [ ]:
filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data - Balanceada.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
795    3  2.52  1.72     2     0  ...      0      1      0   74     True
796    3  2.52  1.72     1     0  ...      0      1      0   71     True
797    2  4.04  2.76     1     0  ...      0      1      0   55     True
798    3  2.48  1.84     1     0  ...      0      1      0   55     True
799    4  3.44  2.16     1     0  ...      0      1      0   57     True

[800 rows x 17 columns]

In [ ]:
data_set_suffle=sk.utils.shuffle(data_set)
data_set_suffle

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
355    3  3.68  3.20     1     0  ...      0      1      0   55    False
131    2  2.12  1.72     1     0  ...      0      1      0   74    False
179    3  3.00  2.36     2     0  ...      0      1      0   60    False
778    3  2.60  2.36     1     0  ...      0      1      0   55     True
226    3  2.96  2.44     1     0  ...      0      1      0   65    False
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
563    3  2.08  1.52     1     0  ...      0      1      0   49     True
111    3  4.00  2.60     1     0  ...      0      1      0   58    False
423    3  5.00  4.04     0     0  ...      0      0      0   60    False
609    4  3.44  2.16     1     0  ...      0      1      0   57     True
779    3  3.68  2.36     0     0  ...      0      1      0   71     True

[800 rows x 17 columns]

In [ ]:
data_set_suffle.describe()

DGN        PRE4        PRE5  ...       PRE30       PRE32        AGE
count  800.000000  800.000000  800.000000  ...  800.000000  800.000000  800.00000
mean     3.143750    3.236487    4.091337  ...    0.853750    0.002500   62.87250
std      0.850877    0.821572   10.530608  ...    0.353578    0.049969    8.83169
min      1.000000    1.440000    0.960000  ...    0.000000    0.000000   21.00000
25%      3.000000    2.622500    2.000000  ...    1.000000    0.000000   57.00000
50%      3.000000    3.080000    2.360000  ...    1.000000    0.000000   62.00000
75%      3.000000    3.760000    2.960000  ...    1.000000    0.000000   70.00000
max      8.000000    6.300000   86.300000  ...    1.000000    1.000000   87.00000

[8 rows x 16 columns]

In [ ]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [ ]:
labels

array([False, False, False, False,  True, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,

In [ ]:
labels_modify = labels.astype('int')

In [ ]:
labels_modify

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [ ]:
labels_temp = []
for x in range(0,len(labels)):
  if labels[x] == False:
    labels_temp.append(0)
  else:
    labels_temp.append(1)

In [ ]:
labels_modify==labels_temp

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
pca = decomposition.PCA(n_components=8)
pca.fit(features)
features = pca.transform(features)
features

array([[-1.29395422e+00,  3.20258820e+00, -2.16373089e+00, ...,
        -3.82419243e-01, -2.24899711e-02,  7.55804527e-01],
       [ 3.02315817e-01,  1.20867261e+01,  1.08198123e-02, ...,
         9.26183542e-01, -2.27382578e-02,  1.98221063e-01],
       [-1.17666108e+00,  4.19418480e+00,  1.34677532e-01, ...,
        -1.64399378e-01, -3.40790987e-01, -2.29666626e-01],
       ...,
       [ 3.26321689e-01,  7.99749155e+00, -8.65391651e-01, ...,
        -6.03088530e-03, -2.58452615e-01, -1.15425076e-01],
       [-5.82901140e-01,  8.15117837e+00, -4.47531030e-01, ...,
        -2.92741575e-01, -3.36547044e-01, -1.40837273e-01],
       [-6.87895292e-01,  6.13496364e+00,  5.88369563e-01, ...,
        -8.33306429e-01,  5.47432188e-02,  6.30660371e-01]])

In [ ]:
scaler = preprocessing.StandardScaler().fit(features)
features = scaler.transform(features)
features

array([[-0.12209924,  0.3663389 , -2.363986  , ..., -0.60107033,
        -0.05889512,  2.04507631],
       [ 0.02852692,  1.38258111,  0.01182119, ...,  1.45573596,
        -0.05954531,  0.53635191],
       [-0.1110313 ,  0.47976604,  0.14714205, ..., -0.25839596,
        -0.89243887, -0.62143816],
       ...,
       [ 0.03079215,  0.91482016, -0.94548438, ..., -0.00947909,
        -0.67681708, -0.31232029],
       [-0.05500333,  0.93240015, -0.4889504 , ..., -0.46011878,
        -0.88132514, -0.3810813 ],
       [-0.06491071,  0.7017686 ,  0.64282366, ..., -1.30975566,
         0.1433576 ,  1.70645787]])

In [ ]:
validation_size = 0.2
seed = 0
X_train, X_validation, Y_train, Y_validation = train_test_split(features,labels_modify, test_size=validation_size, random_state=seed)

In [ ]:
X_train.shape, X_validation.shape, Y_train.shape, Y_validation.shape

((640, 8), (160, 8), (640,), (160,))

In [ ]:
X_train

array([[-0.12375855,  0.13297646, -1.21901757, ..., -0.0706146 ,
         1.30959915, -2.24061119],
       [-0.32198586, -0.28735585, -0.1028443 , ..., -0.59352269,
        -0.24129088,  1.26448093],
       [-0.0474215 ,  0.46467475, -1.22392265, ..., -0.08869584,
         1.11912277, -1.77185265],
       ...,
       [-0.17993929,  0.26219847,  0.98669756, ..., -0.79903025,
         1.16121777, -1.90401901],
       [-0.17993929,  0.26219847,  0.98669756, ..., -0.79903025,
         1.16121777, -1.90401901],
       [ 0.01274053,  0.56743186,  5.30308161, ..., -0.06836801,
         0.56102167,  0.33397401]])

In [ ]:
X_validation

array([[-0.10414659,  0.59845401,  0.02995308, ...,  1.62331051,
        -0.15120001,  0.51839912],
       [-0.49283014, -1.99145004,  1.94247328, ...,  1.50821521,
         0.6137827 ,  0.31831354],
       [-0.14081155, -0.44537691, -0.06317157, ..., -0.74202556,
         1.84809464,  0.09213906],
       ...,
       [-0.10968435,  0.01467946,  1.53948441, ...,  1.61698936,
         0.69887418,  0.4983661 ],
       [-0.29337722, -0.99018496, -0.08499894, ..., -0.01207363,
        -0.99215289, -0.40600769],
       [ 0.29381397,  1.78295135,  0.67989142, ...,  0.30779625,
         0.27517195,  0.54290828]])

In [ ]:
Y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,

In [ ]:
Y_validation

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
seed = 42
scoring = 'accuracy'

models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('MLP', MLPClassifier()))
models.append(('RF', RandomForestClassifier()))
models.append(('DT', DecisionTreeClassifier()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will ra

LR: 0.606250 (0.072214)
LDA: 0.607812 (0.063064)
KNN: 0.778125 (0.042962)
NB: 0.660937 (0.054598)
SVM: 0.710938 (0.055573)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.ma

MLP: 0.725000 (0.053309)
KM: 0.196875 (0.065252)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


RF: 0.945312 (0.018815)
DT: 0.912500 (0.028125)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
