In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from pandas import set_option
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import decomposition
from sklearn import preprocessing

In [3]:
filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
465    2  3.88  2.12     1     0  ...      0      1      0   63    False
466    3  3.76  3.12     0     0  ...      0      1      0   61    False
467    3  3.04  2.08     1     0  ...      0      0      0   52    False
468    3  1.96  1.68     1     0  ...      0      1      0   79    False
469    3  4.72  3.56     0     0  ...      0      1      0   51    False

[470 rows x 17 columns]

In [4]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [6]:
labels = labels.astype('int')
labels

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [7]:
scaler = preprocessing.StandardScaler().fit(features)
features_scaler = scaler.transform(features)

In [8]:
pca = decomposition.PCA(n_components=6)
pca.fit(features_scaler)
feature_PCA_Scaler = pca.transform(features_scaler)

In [9]:
validation_size = 0.2
seed = 7
X_trainScaler, X_validationScaler, Y_trainScaler, Y_validationScaler = train_test_split(feature_PCA_Scaler, labels, 
                                                                                        test_size=validation_size, 
                                                                                        random_state=seed)

In [10]:
KNN = KNeighborsClassifier()
KNN.fit(X_trainScaler, Y_trainScaler)
predictions = KNN.predict(X_validationScaler)

In [11]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.8829787234042553
Matriz de confusion


array([[81,  2],
       [ 9,  2]])

In [13]:
LR = LogisticRegression()
LR.fit(X_trainScaler, Y_trainScaler)
predictions = LR.predict(X_validationScaler)

In [14]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.8617021276595744
Matriz de confusion


array([[81,  2],
       [11,  0]])

In [15]:
DT = DecisionTreeClassifier()
DT.fit(X_trainScaler, Y_trainScaler)
predictions =DT.predict(X_validationScaler)

In [16]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.7659574468085106
Matriz de confusion


array([[69, 14],
       [ 8,  3]])

In [17]:
SVM = SVC()
SVM.fit(X_trainScaler, Y_trainScaler)
predictions = SVM.predict(X_validationScaler)

In [18]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.8829787234042553
Matriz de confusion


array([[83,  0],
       [11,  0]])

In [23]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier()
RF.fit(X_trainScaler, Y_trainScaler)
predictions = RF.predict(X_validationScaler)

In [24]:
print('precision en validacion')
print(accuracy_score(Y_validationScaler, predictions))
print('Matriz de confusion')
confusion_matrix(Y_validationScaler, predictions)

precision en validacion
0.8723404255319149
Matriz de confusion


array([[81,  2],
       [10,  1]])