In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import seaborn as sns


filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
465    2  3.88  2.12     1     0  ...      0      1      0   63    False
466    3  3.76  3.12     0     0  ...      0      1      0   61    False
467    3  3.04  2.08     1     0  ...      0      0      0   52    False
468    3  1.96  1.68     1     0  ...      0      1      0   79    False
469    3  4.72  3.56     0     0  ...      0      1      0   51    False

[470 rows x 17 columns]

In [3]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [4]:
labels

array([False, False, False, False,  True, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,

In [5]:
features

DGN  PRE4  PRE5  PRE6  PRE7  PRE8  ...  PRE17  PRE19  PRE25  PRE30  PRE32  AGE
0      2  2.88  2.16     1     0     0  ...      0      0      0      1      0   60
1      3  3.40  1.88     0     0     0  ...      0      0      0      1      0   51
2      3  2.76  2.08     1     0     0  ...      0      0      0      1      0   59
3      3  3.68  3.04     0     0     0  ...      0      0      0      0      0   54
4      3  2.44  0.96     2     0     1  ...      0      0      0      1      0   73
..   ...   ...   ...   ...   ...   ...  ...    ...    ...    ...    ...    ...  ...
465    2  3.88  2.12     1     0     0  ...      0      0      0      1      0   63
466    3  3.76  3.12     0     0     0  ...      0      0      0      1      0   61
467    3  3.04  2.08     1     0     0  ...      0      0      0      0      0   52
468    3  1.96  1.68     1     0     0  ...      0      0      0      1      0   79
469    3  4.72  3.56     0     0     0  ...      0      0      0      1      0   51

[470 rows x 16 columns]

In [6]:
labels.shape, features.shape, data_set.shape

((470,), (470, 16), (470, 17))

In [7]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(features, labels, test_size=validation_size, random_state=seed)

In [8]:
X_train.shape, X_validation.shape, Y_train.shape, Y_validation.shape

((376, 16), (94, 16), (376,), (94,))

In [9]:
KNN=KNeighborsClassifier()
LR=LogisticRegression()

In [10]:
KNN.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
KNN.score(X_validation,Y_validation)

0.8723404255319149

In [12]:
predic=KNN.predict(X_validation)
predic

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False])

In [13]:
predic==Y_validation

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False])

In [14]:
print(accuracy_score(Y_validation, predic))
print(confusion_matrix(Y_validation, predic))
print(classification_report(Y_validation, predic))

0.8723404255319149
[[82  1]
 [11  0]]
              precision    recall  f1-score   support

       False       0.88      0.99      0.93        83
        True       0.00      0.00      0.00        11

    accuracy                           0.87        94
   macro avg       0.44      0.49      0.47        94
weighted avg       0.78      0.87      0.82        94



In [15]:
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(KNN, features, labels, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % ('KNN', cv_results.mean(), cv_results.std())
print(msg)

KNN: 0.834043 (0.048331)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
