In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from pandas import set_option
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import decomposition
from sklearn import preprocessing



In [3]:
filename = '/content/drive/MyDrive/Proyecto Inteligencia/Resources/Thoracic Surgery Data.csv'
data_set = pd.read_csv(filename)
data_set

DGN  PRE4  PRE5  PRE6  PRE7  ...  PRE25  PRE30  PRE32  AGE  Risk1Yr
0      2  2.88  2.16     1     0  ...      0      1      0   60    False
1      3  3.40  1.88     0     0  ...      0      1      0   51    False
2      3  2.76  2.08     1     0  ...      0      1      0   59    False
3      3  3.68  3.04     0     0  ...      0      0      0   54    False
4      3  2.44  0.96     2     0  ...      0      1      0   73     True
..   ...   ...   ...   ...   ...  ...    ...    ...    ...  ...      ...
465    2  3.88  2.12     1     0  ...      0      1      0   63    False
466    3  3.76  3.12     0     0  ...      0      1      0   61    False
467    3  3.04  2.08     1     0  ...      0      0      0   52    False
468    3  1.96  1.68     1     0  ...      0      1      0   79    False
469    3  4.72  3.56     0     0  ...      0      1      0   51    False

[470 rows x 17 columns]

In [4]:
data_set.describe()

DGN        PRE4        PRE5  ...       PRE30       PRE32         AGE
count  470.000000  470.000000  470.000000  ...  470.000000  470.000000  470.000000
mean     3.095745    3.281638    4.568702  ...    0.821277    0.004255   62.534043
std      0.722309    0.871395   11.767857  ...    0.383529    0.065163    8.706902
min      1.000000    1.440000    0.960000  ...    0.000000    0.000000   21.000000
25%      3.000000    2.600000    1.960000  ...    1.000000    0.000000   57.000000
50%      3.000000    3.160000    2.400000  ...    1.000000    0.000000   62.000000
75%      3.000000    3.807500    3.080000  ...    1.000000    0.000000   69.000000
max      8.000000    6.300000   86.300000  ...    1.000000    1.000000   87.000000

[8 rows x 16 columns]

In [5]:
labels= data_set['Risk1Yr'].values
features = data_set.drop(['Risk1Yr'], axis=1)

In [6]:
labels

array([False, False, False, False,  True, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,

In [7]:
labels_modify = labels.astype('int')

In [8]:
labels_modify

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [9]:
labels_temp = []
for x in range(0,len(labels)):
  if labels[x] == False:
    labels_temp.append(0)
  else:
    labels_temp.append(1)

In [ ]:
labels_modify==labels_temp

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [11]:
pca = decomposition.PCA(n_components=6)
pca.fit(features)
features = pca.transform(features)
features

array([[ -1.92292603,   2.90828443,  -1.05803016,  -2.17170127,
          0.54296957,   0.68688991],
       [ -0.55501533,  11.84231381,  -0.12170816,   0.16926264,
         -0.25704496,   0.8475769 ],
       [ -1.81774495,   3.90762172,  -0.58192181,   0.53963561,
         -0.02629948,  -0.62313929],
       ...,
       [ -0.54854819,  10.79518996,  -0.59294295,  -0.82011972,
          0.87300818,   0.55797858],
       [ -5.82581363, -15.71240023,  -0.87905621,  -0.07147551,
          0.26937471,  -0.03444806],
       [  1.10415764,  11.57704958,   1.06449199,  -0.26337723,
         -0.58326405,   0.66180788]])

In [12]:
scaler = preprocessing.StandardScaler().fit(features)
features = scaler.transform(features)
features

array([[-0.1622945 ,  0.33908128, -1.23268883, -2.83884244,  0.83832255,
         1.08985654],
       [-0.04684316,  1.38071329, -0.14179963,  0.2212597 , -0.39686678,
         1.34481118],
       [-0.15341724,  0.45559553, -0.67798493,  0.70541031, -0.04060531,
        -0.98870637],
       ...,
       [-0.04629734,  1.25862754, -0.69082544, -1.07205844,  1.3478885 ,
         0.88531888],
       [-0.49169729, -1.83193253, -1.02417002, -0.0934326 ,  0.41590341,
        -0.05465714],
       [ 0.09319064,  1.34978573,  1.24021737, -0.34428605, -0.90053556,
         1.05006004]])

In [13]:
validation_size = 0.2
seed = 0
X_train, X_validation, Y_train, Y_validation = train_test_split(features,labels_modify, test_size=validation_size, random_state=seed)

In [14]:
X_train.shape, X_validation.shape, Y_train.shape, Y_validation.shape

((376, 6), (94, 6), (376,), (94,))

In [15]:
X_train

array([[-0.31495134, -1.51296394,  1.88201851, -0.33662069,  0.59011421,
         0.00739556],
       [-0.22098485, -0.23726806,  0.46179794,  0.19915581,  1.34004672,
         0.10195964],
       [-0.11157399,  0.56459078, -1.12309847, -2.81889283,  0.70663146,
         1.41877803],
       ...,
       [-0.05539042,  1.14134193, -0.86728221, -0.18352786,  0.81911417,
        -0.14868152],
       [-0.34800534, -1.03572007, -0.4769681 , -0.26918453,  0.23173389,
         0.09414241],
       [-0.15860489,  0.10292252, -0.76754593, -1.2110312 , -0.71409694,
        -0.48936001]])

In [16]:
X_validation

array([[-2.35487481e-01,  1.18383691e-01, -1.10102341e+00,
        -8.50973394e-02,  8.27600477e-01, -2.05398169e-01],
       [ 7.18126065e-02,  1.35311007e+00,  1.18405132e+00,
        -1.38657149e-01, -5.34832293e-01, -1.55847448e+00],
       [-1.34418381e-01,  9.86784939e-02,  5.79016822e-01,
         8.39809307e-01,  4.06061908e-01,  1.71387392e+00],
       [-6.96477650e-02,  7.94361019e-01,  1.47534238e-02,
         1.24100283e+00, -1.19142201e+00,  7.30137941e-01],
       [-9.16558677e-02,  9.14235867e-01,  8.56219992e-01,
         2.08886878e+00,  1.79448519e+00, -3.83564354e-01],
       [-1.46168257e-01,  3.33458348e-01, -5.98699765e-01,
        -6.98536579e-01,  1.19096547e+00, -1.46148427e+00],
       [ 5.50087436e+00, -1.56876400e+00, -1.41852187e+00,
        -1.47780812e+00, -1.01194766e+00,  1.59566555e+00],
       [-1.97643885e-01, -6.50123405e-03, -3.90397215e-01,
         6.03348344e-01, -2.30211093e-01, -9.76029287e-01],
       [-2.92576010e-01, -9.28275890e-01,  4.701

In [17]:
Y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
Y_validation

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0])

In [19]:
seed = 42
scoring = 'accuracy'

models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('MLP', MLPClassifier()))
models.append(('KM', KMeans()))
models.append(('RF', RandomForestClassifier()))
models.append(('DT', DecisionTreeClassifier()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will ra

LR: 0.855974 (0.051849)
LDA: 0.855974 (0.051849)
KNN: 0.818848 (0.038441)
NB: 0.773684 (0.064900)
SVM: 0.861309 (0.052483)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLP: 0.856046 (0.045803)
KM: 0.119844 (0.062557)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


RF: 0.848080 (0.045559)
DT: 0.739189 (0.048230)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
